FROM mono:5

ENV DOCUMENTATION_DEPLOY_USERNAME insert-username-here
ENV DOCUMENTATION_DEPLOY_TOKEN insert-personal-access-token-here

# We need to install the .NET Core SDK alongside Mono to get proper code analysis:
ENV DOTNET_SKIP_FIRST_TIME_EXPERIENCE 1
WORKDIR /tmp/
RUN apt-get update && apt-get install -y wget unzip git apt-transport-https
RUN wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN apt-get update && apt-get install -y dotnet-sdk-3.1

# Install DocFX to /opt/docfx/:
WORKDIR /opt/docfx/
RUN wget -q https://github.com/dotnet/docfx/releases/download/v2.48/docfx.zip -O docfx.zip
RUN unzip docfx.zip

WORKDIR /project/
# Note: this Dockerfile assumes that the context is the root of the project.
COPY . .

# Build the project to ensure packages and project metadata are properly updated:
WORKDIR /project/src/FluentDbTools/
RUN dotnet restore FluentDbTools.sln && dotnet build FluentDbTools.sln

# Finally, run DocFX and commit the updated documentation:
WORKDIR /project/
CMD /project/doc/publishDocs.sh