//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentDbTools.Migration.Oracle.CustomProcessor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluentDbTools.Migration.Oracle.CustomProcessor.SqlResources", typeof(SqlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create user {SchemaName} identified by &quot;{SchemaName}&quot;
        ///enable editions account lock;
        ///
        ///declare
        ///  ROLE_NAME varchar2(50) := &apos;{SchemaPrefix}_TABLE_ROLE&apos;;
        ///begin
        ///
        ///  execute immediate &apos;create role &apos; || ROLE_NAME;
        ///exception
        ///  when others then
        ///    --&quot;ORA-01921: role name &apos;x&apos; conflicts with another user or role name&quot;
        ///    if sqlcode = -01921 then 
        ///      null;
        ///    else
        ///      raise;
        ///    end if;
        ///end;
        ///
        ///
        ///-- hei hei
        ///-- aho
        ////* 
        ///create role {SchemaPrefix}_TABLE_ROLE;
        ///*/
        ///-- CREATE ROLE &apos;{SchemaPrefix}_T [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CreateSchemaSql {
            get {
                return ResourceManager.GetString("CreateSchemaSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare
        ///begin
        ///	-- {CommonSchemaName}.cpsesjon.dwp_logginn(&apos;MIGRATION-{User}&apos;);
        ///    {AuthCodeSchemaName}.cpSesjon.dwp_logginn (&apos;MIGRATION-{User}&apos;);
        ///	{AuthCodeSchemaName}.cpsesjon.dwp_Oppgradering;
        ///end;
        ////
        ///.
        /// </summary>
        public static string LogonScriptSql {
            get {
                return ResourceManager.GetString("LogonScriptSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Title = Create schemaprefix {SchemaName}.{SchemaPrefixId}
        ///-- SCHEMAPREFIXGID &apos;{SchemaPrefixUniqueId}&apos; is extracted from UTV18.WORLD
        ///begin
        ///  update {CommonSchemaName}.coSchemaPrefix
        ///  set    schema      = &apos;{SchemaName}&apos;,
        ///         VALIDPREFIX = &apos;{SchemaPrefixId}&apos;,
        ///         OBJECT_TYPE = &apos;TABLE&apos;,
        ///         PREFIX_TYPE = &apos;O&apos;,
        ///         REMARKS     = null
        ///  where  SCHEMAPREFIXGID = &apos;{SchemaPrefixUniqueId}&apos;;
        ///
        ///  if sql%rowcount=0 then 
        ///            insert into {CommonSchemaName}.coSchemaPrefix
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SchemaPrefixSql {
            get {
                return ResourceManager.GetString("SchemaPrefixSql", resourceCulture);
            }
        }
    }
}
