# Run "docker build -f Dockerfile -t <docker_image> ." in powershell to build this Dockerfile locally.

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY . .

ENV VERSION=1.0.0
ENV NUGET_FOLDER=output/nuget/signed
ENV API_KEY=Admin:Admin

ENTRYPOINT ls ${NUGET_FOLDER}/*.${VERSION}.nupkg | xargs -I % sh -c 'dotnet nuget push -k ${API_KEY} %'

    
