FROM microsoft/dotnet:2.1-sdk AS build

ARG TEST_FOLDER
ENV RUN_TEST_FOLDER=$TEST_FOLDER

WORKDIR /src
COPY . .

COPY ./test.proj.template ./${RUN_TEST_FOLDER}/test.proj
RUN dotnet build ./${RUN_TEST_FOLDER} --verbosity=minimal
ENTRYPOINT dotnet test ./${RUN_TEST_FOLDER} --verbosity=normal --no-build