FROM microsoft/dotnet:2.2-sdk AS build

ARG TEST_FOLDER
ENV RUN_TEST_FOLDER=$TEST_FOLDER
ENV TEAMCITY_PROJECT_NAME = ${TEAMCITY_PROJECT_NAME}

WORKDIR /src
COPY . .

ENV TZ=Europe/Oslo
ENV RUNNING_IN_CONTAINER=true
ENV DATABASE=postgres

COPY ./test.proj.template ./${RUN_TEST_FOLDER}/test.proj
RUN dotnet build ./${RUN_TEST_FOLDER} --verbosity=minimal
ENTRYPOINT dotnet test ./${RUN_TEST_FOLDER} --verbosity=normal --no-build