# Run "docker build -f Dockerfile -t <docker_image> ." in powershell to build this Dockerfile locally.

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY . .

ARG VERSION=1.0.0
ARG NUGET_FOLDER=nuget
ARG SOLUTION_NAMESPACE=MySolutioNamespace
ARG SOLUTION_FOLDER=$SOLUTION_NAMESPACE

ENV SOLUTION_FOLDER=$SOLUTION_FOLDER

RUN ls ${SOLUTION_FOLDER}/*/*/${SOLUTION_NAMESPACE}.*.csproj | xargs -I % sh -c 'dotnet pack % -c Release /p:Version=${VERSION} /p:PackageVersion=${VERSION}'
RUN if [ -d "${NUGET_FOLDER}" ]; then rm -Rf ${NUGET_FOLDER}; fi
RUN mkdir -p ${NUGET_FOLDER}
RUN ls ${SOLUTION_FOLDER}/*/*/bin/Release/*.nupkg | xargs -I % sh -c 'cp % ${NUGET_FOLDER}/$(basename %)'

    
